import * as seedrandom from 'seedrandom';

export const itemPrefixes = [
'Platina',
'Friss',
'a legkorszerubb',
'osi',
'Kezzel keszitett',
'oraszerkezet',
'legendas',
'Grillezett',
'Nyers',
'Indigo',
'zsebmeret',
'3 napja',
'Akorul',
'Hamis',
'Mar hasznalt',
'torott',
'kereskedelmi forgalomban kaphato',
'mertek utani',
'kereskedelmi',
'Made by Microsoft',
'Made by Apple',
'Emberi technologia kombinalasaval keszult',
'Made in 2018',
'Korulbelul 500 kg sulyu',
'luxus',
'Rothadt',
'mesterseges intelligenciaval felszerelve',
'Anti gravitacio',
'osszecsukhato',
'hordozhato',
'Genetikai rekombinacio',
'Megszerezte a repulesi kepesseget',
'tiszta arany',
'atlatszo',
'csillogo',
'sziv alaku',
'mozgo',
'vagd felbe',
'USB csatlakozoval',
'osi',
'atkozott',
'elvarazsolt',
'Egy nap vitamint kaptam',
'harapas',
'Fantom',
'virtualis',
'Nuklearis',
'magasan kepzett',
'A tomloc legmelyen talaltak',
'Tulvilagi',
'idegen',
'rejtelyes',
'torzitja a teridot',
'Furcsa zaj',
'szetoszlatni',
'Plasmaized',
'Alacsony az esely a robbanasra becsapodaskor',
'hipotetikus',
'mergezo',
'igaz',
'Ultimate',
'csokolade',
'szag',
'lukteto',
'Furcsa',
'negyzet',
'Tombol',
'alom',
'Sotet',
'sotet',
'Zart',
'halal',
'fagyott',
'demoni',
'Tiltott',
'holografikus',
'hidraulikus',
'Nem fuszeres, de egy kicsit fuszeres',
'megegett',
'univerzum',
'elektronikus',
'Pozitron',
'kvantummechanika',
'elosztott',
'tojastekercs',
'kovetkezo generacios',
'toltott',
'osi',
'High Resilience',
'Olcso kiadas',
'ragados',
'puha',
'szaraz',
'nyirkos',
'lejart',
'A pokolbol szarmazom',
'jobb fokhagyma',
'Radioaktiv',
'fraktal',
'rekurziv',
'Neha kettevalik',
'eltunnek',
'Egyenletes linearis mozgas vegrehajtasa',
'rontgenbesugarzas',
'vonaglo',
'metafizikai',
'ragados',
'hideg',
'forro',
'hatalmas',
'nano meret',
'puha',
'Bogar',
'mesterseges',
'termeszetes',
'beveve',
'csokoladebevonat',
'Antibakterialis specifikacio',
'tuzallo',
'eros',
'Kegyetlen',
'Szuper',
'Konnyusulyu',
'Nemzeti kincs',
'divatos',
'nyolc karatos',
'hasznalt',
'uj',
'szeretett feleseg',
'markas',
'Szorzas',
'purupuru',
'squishy',
'tobbcelu',
'Fuszeres',
'halado',
'retro',
'szuret',
'jogi',
'premiummal',
'deka',
'Giga',
'szennyezett',
'Garantalt minoseg',
'AppleCare+ regisztralva',
'Rossz',
'tervezok',
'elbuvolo',
'Kivancsi vagyok, ez csoda-e',
'fenyes',
'ragados',
'izom',
'tulhuzott',
'szervetlen',
'avantgarde',
'Gyanus',
'rejtelyes',
'Peneszes',
'oregedes',
'Aluminium ontveny',
'akvakultura',
'szornyu',
'nagyon',
'aranyos',
'Digitalis',
'analog',
'Hello',
'Szines',
'Elektromos',
'nincs hitbox',
'Beragadt',
'egyszer szaz evben',
'ledus',
'Hi-Res',
'Valtozo',
'Eheto',
'AZ ',
'bizonyos',
'romlo',
'elpusztul',
'A visszateritesi egyutthato e>1',
'surlodasi tenyezo 0',
'elszabadult',
'nagy',
'kicsi',
'kapzsi',
'dagad',
'merites',
'ego',
'magas nyomasu',
'Rendellenes',
'durva talaj',
];

export const items = [
'padlizsan',
'Paradicsom',
'uborka',
'krumpli',
'Grillezett rizsteszta',
'derek',
'susi',
'tok',
'Yukichi',
'kilobar',
'Aluminium',
'Natrium',
'Magnezium',
'Plutonium',
'Kis erem',
'tejesdoboz',
'PET palackok',
'sutik',
'csokolade',
'Szolnokruhak',
'narancs',
'terdig ero',
'antianyag kondenzator',
'reszecskegyorsito',
'mikroprocesszor (4 mag, 8 szal)',
'Atomeromu',
'4. reteg kapcsolo',
'pufferlanc',
'Positron Brain',
'bolygo',
'Theremin',
'csigakerek',
'Megyer',
'kanalkerekes kotrogep',
'demon mag',
'Gameboy Advance',
'kvantumszamitogep',
'anamorf lencse',
'Rejtelyes leny, aki elobujt a szekrenybol',
'okostelefon',
'ora',
'puding',
'Gabriel trombitaja',
'Menger szivacs',
'kezi fono',
'Hiperkocka',
'epulet',
'energia ital',
'egerkurzor',
'Szemuveg',
'Tonhal',
'Szemetes',
'fogpiszkalo',
'Kinai evopalcikak',
'elszivo ventilator',
'muanyag kupak',
'Wave Dissipating Block',
'Pizza',
'fogkrem',
'ures kanna',
'kulcstarto',
'Gyonyoru lany szoke hajjal es kek szemekkel',
'SD kartya',
'Ajakbalzsam',
'Csokolade kornet csokolade nelkul',
'madarinfluenza',
'automata',
'nehez',
'laptop',
'marha rantas',
'Sake Cheese',
'Gyemant',
'targy',
'Holdko',
'Szingularitas',
'neutroncsillag',
'folyekony',
'muhold',
'cukkini',
'fekete dolgok',
'feher dolgok',
'piros cucc',
'kerek dolog',
'negyzet',
'kartyaszeru dolog',
'gaz',
'Ceruza',
'radir',
'Kard',
'a palca',
'mezogazdasagi termekek',
'fem iszap',
'polip lab',
'gomba',
'Nameko',
'konzerv chuhai',
'koromvagas',
'Fultisztitas',
'Pluss baba',
'Tyrannosaurus',
'Hugyuti ko',
'Enter gomb',
'edeny',
'Higany',
'DHMO',
'viz',
'Fold',
'Kontinens',
'Dobokocka',
'Kulteri egyseg',
'hidraulikus emelo',
'tapioka',
'vecepapir mag',
'Kartondoboz',
'Haniwa',
'golyostoll',
'mechanikus ceruza',
'atomok',
'univerzum',
'elemi reszecskek',
'Szezamolaj',
'Tojas a rizs folott',
'Sotet anyag',
'Fekete lyuk',
'Sun',
'kvarcuveg',
'gat',
'virus',
'bakteriumok',
'Betonives gat',
'Concrete Gravity Dam',
'flush valve',
'Vibraslap',
'targy',
'Atomeromu',
'Reaktor',
'Eratosthenes szita',
'katodsugarcso',
'Tachyon',
'Russell teaskanna',
'Elektronika',
'TNT',
'Poligon',
'levego',
'RTX 3090',
'Mechanikus ceruza vezetek',
'Rosette-i ko',
'Caps Lock billentyu',
'ures',
'UFo',
'NumLock kulcs',
'Radioaktiv hulladek',
'Mars',
'Uranium',
'Centrifuga',
'meghatarozatlan',
'nulla',
'NaN',
'[objektum objektum]',
'nulla szelessegu terkoz',
'teljes szelessegu ter',
'dob',
'ko szobor',
'Slime',
'P pont',
'🤯',
'Kinnotama',
'hajlithato lemez',
'fuggo tekercs',
'JavaScript konzol',
'Internet bongeszo',
'Mitokondrium',
'Helium',
'feherje',
'Kapszaicin',
'Mozgolepcso',
'fuzios reaktor',
'geotermikus eromu',
'apartman',
'lavafeny',
'Galileo homero',
'Sugarzasmero',
'Homokkep',
'viharuveg',
'Newton Cradle',
'A datolyaszilva magjanak foldimogyoro resze',
'Hengeres tomb csuszashoz',
'futon',
'agynemu',
'balvany',
'Az Univerzum',
'Dagoba',
'Kotatsu',
'Zokni (egy elveszett)',
'Egeszsegbiztositasi kartya',
'Telefonkartya',
'Zongora fekete billentyuk',
'AC adapter',
'DVD',
'varosi busz',
'bazisallomas',
'404 nem talalhato',
'JSON',
'Gobelin',
'Konyv',
'ko szobor',
'osi dokumentumok',
'tekercs',
'Misskey',
'Mogimogi gyumolcs',
'<tetszoleges karakterlanc itt>',
'Fosszilis',
'aknafedel',
'csap',
'szakall',
'1 jenes erme',
'violinkulcs',
'Portal',
'a bal nyitott zarojel fele',
'elektromos masszirozo',
'felugro hirdetesek',
'README.txt',
'elkovetni',
'prime',
'Feladatkezelo',
'a zsivaj',
'szenhidratok',
'Dodekaeder',
'Klein vaza',
'Moebius szalag',
'Orichalcum',
'iszap',
'racs',
'Hurok fuzere',
'Super-Kamiokande',
];

export const and = [
'nek alcazva',
'belep',
'tetszik',
'tetetni magat',
'elnyomni',
'kiszolgalt',
'lovagolva',
];

export function genItem(seedOrRng?: (() => number) | string | number) {
	const rng = seedOrRng
		? typeof seedOrRng === 'function'
			? seedOrRng
			: seedrandom(seedOrRng.toString())
		: Math.random;

	let item = '';
	if (Math.floor(rng() * 5) !== 0) item += itemPrefixes[Math.floor(rng() * itemPrefixes.length)];
	item += items[Math.floor(rng() * items.length)];
	if (Math.floor(rng() * 10) === 0) {
		item += and[Math.floor(rng() * and.length)];
		if (Math.floor(rng() * 5) !== 0) item += itemPrefixes[Math.floor(rng() * itemPrefixes.length)];
		item += items[Math.floor(rng() * items.length)];
	}
	return item;
}
